#!/bin/bash

# Ad Improvements Testing - Manual Verification Guide
# Run this after starting dev server with: pnpm dev

echo "════════════════════════════════════════════════════════════"
echo "  AD IMPROVEMENTS - MANUAL TESTING GUIDE"
echo "════════════════════════════════════════════════════════════"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 PREREQUISITE:${NC}"
echo "  Dev server must be running: pnpm dev"
echo "  Open http://localhost:3000 in browser"
echo ""

echo "════════════════════════════════════════════════════════════"
echo -e "${GREEN}TEST 1: Session Persistence${NC}"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Open http://localhost:3000 in NEW incognito window"
echo "2. Open DevTools → Application → Session Storage"
echo "3. Scroll to 50% of page"
echo "4. Wait for popup ad to appear"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Session storage shows key: 'popup-ad-shown-session' = '1'"
echo "   - Popup appears once"
echo ""
echo "5. Close popup and navigate to different page"
echo "6. Scroll again to 50%"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Popup does NOT appear again"
echo "   - Session storage still shows key = '1'"
echo ""
echo "7. Close browser completely"
echo "8. Open new incognito window at localhost:3000"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Session storage is empty (new session)"
echo "   - Popup appears again after scrolling"
echo ""
read -p "Press ENTER when Test 1 complete..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo -e "${GREEN}TEST 2: Trigger Coordination (No Double-Show)${NC}"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Clear session storage (DevTools → Application → Clear)"
echo "2. Navigate to any article page (e.g., /category/leadership)"
echo "3. Scroll to 50% depth → popup should appear"
echo "4. Close popup"
echo "5. Continue scrolling to 80% (past in-article ads)"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Popup appears ONLY at 50% scroll"
echo "   - Does NOT appear again when passing in-article ads"
echo "   - Session storage key prevents second trigger"
echo ""
read -p "Press ENTER when Test 2 complete..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo -e "${GREEN}TEST 3: Pause Carousel on Hover${NC}"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Clear session storage"
echo "2. Trigger popup (scroll to 50%)"
echo "3. Wait for carousel to start rotating (5 second interval)"
echo "4. Hover mouse over popup ad"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Carousel rotation PAUSES while hovering"
echo "   - Current slide stays visible"
echo ""
echo "5. Move mouse away from popup"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Carousel rotation RESUMES"
echo "   - Auto-advances after 5 seconds"
echo ""
read -p "Press ENTER when Test 3 complete..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo -e "${GREEN}TEST 4: Optimized Sidebar Queries${NC}"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Open DevTools → Network tab"
echo "2. Filter by: '2f93fcy8.api.sanity.io'"
echo "3. Clear network log"
echo "4. Navigate to article page with sidebar ad"
echo "5. Wait for page to fully load"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Single Sanity query for sidebar ad (not two separate queries)"
echo "   - Query uses 'coalesce()' for fallback logic"
echo "   - Response returns either active ad OR Brabus fallback"
echo ""
echo "To verify query structure:"
echo "6. Click on Sanity request → Payload tab"
echo "7. Look for 'coalesce' in query string"
echo ""
read -p "Press ENTER when Test 4 complete..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo -e "${GREEN}TEST 5: Environment Variable Fallback${NC}"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "VERIFY .env.local:"
cat ../.env.local | grep "NEXT_PUBLIC_FALLBACK_AD_ID"
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Variable exists in .env.local"
echo "   - Value: clNGIHR7teKIrj4L6FqRKA (Brabus ad ID)"
echo ""
echo "VERIFY CODE USAGE:"
echo ""
grep -n "process.env.NEXT_PUBLIC_FALLBACK_AD_ID" ../components/Ad.tsx
echo ""
echo "✅ EXPECTED RESULTS:"
echo "   - Ad.tsx uses env variable with fallback"
echo "   - Format: process.env.NEXT_PUBLIC_FALLBACK_AD_ID || 'clNGIHR7...'"
echo ""
read -p "Press ENTER when Test 5 complete..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo -e "${GREEN}CODE QUALITY CHECKS${NC}"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "Checking TypeScript compilation..."
cd ..
pnpm tsc --noEmit 2>&1 | grep -E "error TS|Found 0 errors" | head -5

echo ""
echo "Checking for linting issues..."
pnpm eslint components/Ad*.tsx hooks/useAdTrigger.ts store/adStore.ts --quiet 2>&1 | head -10 || echo "✅ No lint errors"

echo ""
echo "════════════════════════════════════════════════════════════"
echo -e "${GREEN}✅ ALL TESTS COMPLETE${NC}"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Summary of Fixes Verified:"
echo "  ✓ Session persistence (popup shows once per session)"
echo "  ✓ Trigger coordination (no double-show)"
echo "  ✓ Pause on hover (better UX)"
echo "  ✓ Optimized queries (50% reduction)"
echo "  ✓ Env variable fallback (configurable)"
echo ""
