/**
 * The Spider (Issue #32) - v2.0 (Email Edition)
 * 
 * A recursive crawler that patrols the site for broken links (404s).
 * Sends a daily report to the administrator.
 */

import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
import path from 'path';
// @ts-ignore - CommonJS import
import { logSystemStatus } from './utils/sanity-logger.js';

// Load Environment Variables
// Load Environment Variables (Graceful fallback for CI)
const fs = require('fs');
const envPath = path.resolve(process.cwd(), '.env.local');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
} else {
  console.log('ℹ️  .env.local not found. Relying on process.env (CI Mode).');
}

const BASE_URL = process.env.BASE_URL || 'https://csuitemagazine.global';
const MAX_PAGES = 2000;
const CONCURRENCY = 10;

// Email Configuration
const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASS = process.env.EMAIL_PASS;
const EMAIL_TO = process.env.EMAIL_TO || 'csuitebrandagency@gmail.com';

// Debug Logging
console.log(`📧 Config: User=${EMAIL_USER ? '***' : 'MISSING'}, Pass=${EMAIL_PASS ? '***' : 'MISSING'}`);

// State
const visited = new Set<string>();
const queue: string[] = [BASE_URL];
const brokenLinks: { source: string, target: string, status: number }[] = [];

// Helper: Navbar for terminal
function normalize(url: string): string {
  try {
    const u = new URL(url);
    u.hash = ''; // Ignore fragments
    if (u.pathname.endsWith('/') && u.pathname.length > 1) {
      u.pathname = u.pathname.slice(0, -1);
    }
    return u.toString();
  } catch {
    return '';
  }
}

// Helper: Extract Links
function extractLinks(html: string, baseUrl: string): string[] {
  const links: string[] = [];
  const regex = /href=["']([^"']+)["']/g;
  let match;
  while ((match = regex.exec(html)) !== null) {
    let href = match[1];
    if (href.startsWith('/')) href = `${baseUrl}${href}`;
    if (!href.startsWith('http')) continue;
    
    if (href.startsWith(baseUrl)) {
      links.push(href);
    }
  }
  return links;
}

// Helper: Send Report
async function sendReport(scanned: number, failures: any[]) {
  if (!EMAIL_USER || !EMAIL_PASS) {
    console.warn('⚠️  Skipping Email: EMAIL_USER/PASS not set.');
    return;
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user: EMAIL_USER, pass: EMAIL_PASS }
  });

  // Verify connection first
  try {
    await transporter.verify();
  } catch (err) {
    console.error('❌ SMTP Connection Verification Failed:', err);
    return;
  }

  const isSuccess = failures.length === 0;
  const emoji = isSuccess ? '✅' : '🔥';
  const subject = `${emoji} The Spider Report: ${isSuccess ? 'Clean' : 'Broken Links Detected'} (${new Date().toLocaleDateString()})`;
  
  const failList = failures.map(f => `<li>[${f.status}] <a href="${f.target}">${f.target}</a> (Found via Queue)</li>`).join('');

  const html = `
    <h2>The Spider Patrol Report</h2>
    <p><strong>Target:</strong> ${BASE_URL}</p>
    <p><strong>Pages Scanned:</strong> ${scanned}</p>
    <p><strong>Status:</strong> ${isSuccess ? '<span style="color:green; font-weight:bold;">HEALTHY</span>' : '<span style="color:red; font-weight:bold;">CRITICAL ISSUES FOUND</span>'}</p>
    
    ${!isSuccess ? `<h3>🚨 Broken Links (${failures.length})</h3><ul>${failList}</ul>` : '<p>No broken links detected via recursive crawl.</p>'}
    
    <hr>
    <p><small>Generated by The Spider (Ralph Protocol v2.6)</small></p>
  `;

  try {
    await transporter.sendMail({
      from: `"The Spider Bot" <${EMAIL_USER}>`,
      to: EMAIL_TO,
      subject,
      html
    });
    console.log(`📧 Report sent to ${EMAIL_TO}`);
  } catch (err) {
    console.error('❌ Failed to send email:', err);
  }
}

async function crawl() {
  console.log(`🕷️ The Spider v2.0 is spinning... Target: ${BASE_URL}\n`);
  
  let processed = 0;
  
  while (queue.length > 0 && processed < MAX_PAGES) {
    const batch = queue.splice(0, CONCURRENCY);
    const promises = batch.map(async (url) => {
      if (visited.has(normalize(url))) return;
      visited.add(normalize(url));
      processed++;
      
      try {
        const res = await fetch(url);
        process.stdout.write(`Checked [${res.status}] ${url}\n`);

        if (res.status >= 400) {
          brokenLinks.push({ source: 'queue', target: url, status: res.status });
          return;
        }

        const contentType = res.headers.get('content-type') || '';
        if (contentType.includes('text/html')) {
          const html = await res.text();
          const children = extractLinks(html, BASE_URL);
          children.forEach(child => {
            const n = normalize(child);
            if (!visited.has(n) && !queue.includes(child)) {
              queue.push(child);
            }
          });
        }
      } catch (err) {
        console.error(`❌ Network Error on ${url}:`, err);
        brokenLinks.push({ source: 'queue', target: url, status: 0 });
      }
    });

    await Promise.all(promises);
  }

  console.log(`\n🕸️ Crawl Complete. Scanned ${processed} pages.`);
  
  // Send Email Report (Regardless of status)
  await sendReport(processed, brokenLinks);

  if (brokenLinks.length > 0) {
    console.error(`\n🔥 CRITICAL: Found ${brokenLinks.length} Broken Links!`);
    // Log Failure
    await logSystemStatus('the-spider', 'FAILURE', `Crawl finished with ${brokenLinks.length} broken links.`, { brokenLinkCount: brokenLinks.length });
    process.exit(1); 
  } else {
    console.log("\n✅ Web Integrity Verified.");
    // Log Success
    await logSystemStatus('the-spider', 'SUCCESS', `Crawl complete. ${processed} pages scanned. Zero broken links.`, { pagesScanned: processed });
    process.exit(0);
  }
}

crawl();
